version: '3.8'

services:
  rasa:
    image: uniamigo:rasa 
    container_name: rasa_server
    ports:
      - "5005:5005"  
      - "5055:5055"  
    environment:
      - DB_USER=root
      - DB_PASSWORD=your_password_here
      - DB_NAME=uniamigo
      - DB_HOST=mariadb
      - SECRET_KEY=UniAmigo4Ever
      - MASTER_TOKEN=your_token_here
    depends_on:
      - mariadb  
    volumes:
      - ./UniAmigoModel:/app/UniAmigoModel
    command: >
      /bin/bash -c "
      source /app/UniAmigoModel/uniamigo/bin/activate &&
      rasa run --enable-api --cors '*' --debug & 
      rasa run actions --actions UniAmigoModel.model.actions"

  mariadb:
    image: mariadb:10.5
    container_name: mariadb_server
    environment:
      MYSQL_ROOT_PASSWORD: your_password_here
      MYSQL_DATABASE: uniamigo
      MYSQL_USER: root
      MYSQL_PASSWORD: your_password_here
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rasa

volumes:
  mariadb_data:
    driver: local
